//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalfuORM.Main
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CalfuEntities : DbContext
    {
        public CalfuEntities()
            : base("name=CalfuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMENTARIO> COMENTARIO { get; set; }
        public virtual DbSet<MAIN_CONFIG> MAIN_CONFIG { get; set; }
        public virtual DbSet<ME_GUSTA> ME_GUSTA { get; set; }
        public virtual DbSet<TIPO_OBRA> TIPO_OBRA { get; set; }
        public virtual DbSet<USER_MSTR> USER_MSTR { get; set; }
        public virtual DbSet<OBRA_MSTR> OBRA_MSTR { get; set; }
    }
}
