//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalfuORM.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class ME_GUSTA
    {
        public int MEGUSTA_ID { get; set; }
        public string VIEWER_NICKNAME { get; set; }
        public int OBRA_ID { get; set; }
        public string MEGUSTA { get; set; }
    }
}
